### ISSUE TITLE
Support for Dropwizard annotations

### ISSUE THREAD

**Issue by darylteo** [katharsis-project/katharsis-rs#14]
Currently, Katharsis doesn't support any of the Dropwizard annotations on its ResourceRepositories. Examples are @UnitOfWork and Timed. 

I suspect this is due to katharsis-rs simply proxying requests to the katharsis-core?

**Comment by meshuga** [comment]
As far as I know annotations like `UnitOfWork` or `Timed` are possible only for Jersey resource methods (https://github.com/dropwizard/dropwizard/issues/1240).
I think all of these problems (transactions, metrics) you should implement on your own using IoC/AOP.
