### ISSUE TITLE
KatharsisFilter should not mask WebApplicationException

### ISSUE THREAD

**Issue by broglep-koubachi** [katharsis-project/katharsis-rs#15]
We have authorization code that throws e.g. ```ForbiddenException``` inside the Katharsis repository.
The code at https://github.com/katharsis-project/katharsis-rs/blob/development/src/main/java/io/katharsis/rs/KatharsisFilter.java#L74-L79 transforms this into a 500 internal server error.

Suggested solution:
```
    try {
        dispatchRequest(requestContext);
    } catch (Exception e) {
         if (e instanceof WebApplicationException) {
            throw e;
         } else{
            throw new WebApplicationException(e);
         }
    }
```

**Comment by meshuga** [comment]
Within minutes v1.0.2 should be on maven central.

**Comment by broglep-koubachi** [comment]
:+1: thanks for the fast fix
