### ISSUE TITLE
KatharsisFilter should ignore non-jsonapi requests

### ISSUE THREAD

**Issue by broglep-koubachi** [katharsis-project/katharsis-rs#18]
We have a scenario where we have an separate regular JAX-RS resource located at the same url location as a katharsis resource. The JAX-RS resource only consumes binary data (POST of image file) and the rest of the API should ideally be handled by katharsis.

Currently when doing a POST request with binary data, katharsis crashes during the attempt to deserialize the input stream to json.

**Comment by broglep-koubachi** [comment]
A simple check like ```requestContext.getMediaType().isCompatible(JsonApiMediaType.APPLICATION_JSON_API_TYPE)```should do trick

**Comment by meshuga** [comment]
Thanks!
